name: build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          working-directory: ./analyzer

      - name: Set up Python
        run: uv python install

      - name: Cache API data
        uses: actions/cache@v4
        with:
          path: analyzer/.cache.sqlite
          # This is a trick to get a "rolling" cache that updates on every run.
          # See: github.com/actions/cache/blob/main/tips-and-workarounds.md#update-a-cache
          key: weather-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            weather-${{ runner.os }}

      - name: Run Analyzer
        run: uv run --directory analyzer main.py
