name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  build:
    uses: ./.github/workflows/build.yml

  preview:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needs to push to gh-pages branch

    steps:
      - uses: actions/checkout@v4 # Checkout is needed by the preview action

      # Order matters: checkout will remove the dist/ directory, so we need to
      # download the artifact after checking out.
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact-name }}
          path: dist/

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./dist/
