name: Run Gleam Tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  OTP_VERSION: "28"
  GLEAM_VERSION: "1.13.0"
  REBAR3_VERSION: "3"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./www

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up Gleam Environment
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          gleam-version: ${{ env.GLEAM_VERSION }}
          rebar3-version: ${{ env.REBAR3_VERSION }}

      - run: gleam deps download

      - name: Run Tests
        run: gleam test

      - name: Check Formatting
        run: gleam format --check src test
